apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dnpk7cvtf-go 
  janus-idp.io/tekton: dnpk7cvtf-go
  backstage.io/kubernetes-id: dnpk7cvtf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dnpk7cvtf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml